### ISSUE TITLE
Game Tutorial

### ISSUE THREAD

**Issue by TenmaUchiyama** [TenmaUchiyama/BombPassing#7]
# Outline 
Design the tutorial of the game. 

# Tasks
- [ ] Add old paper texture / background behind text
Something like this:
![image](https://github.com/TenmaUchiyama/BombPassing/assets/10163529/05a16746-61f4-42fb-90c0-9f675a7fcf67)

# Duration

**Comment by kokoL152** [comment]
show the instruction panel after clicking on option button
